# Generated by Django 3.1 on 2021-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_work',
            field=models.BooleanField(default=False, verbose_name='投票中'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日'),
        ),
    ]
