# Generated by Django 3.1 on 2021-09-14 13:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0002_auto_20210914_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='pass_band',
            field=django_mysql.models.ListCharField(models.CharField(max_length=150), blank=True, max_length=7550, size=50),
        ),
    ]
