# Generated by Django 3.1 on 2021-09-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0004_auto_20210914_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='announce',
            field=models.BooleanField(default=False, verbose_name='結果の公開'),
        ),
    ]
