# Generated by Django 3.1 on 2021-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0005_vote_announce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suffrage',
            field=models.BooleanField(default=False, verbose_name='投票権'),
        ),
    ]
