# Generated by Django 3.1 on 2021-09-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0006_auto_20210918_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='is_work',
            new_name='is_active',
        ),
    ]
