# Generated by Django 3.1 on 2021-09-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suffrage',
            field=models.BooleanField(default=True, verbose_name='投票権'),
        ),
    ]
